services:
    jupyterlab:
        build: .
        image: jupyter
        init: true
        ports:
            - "8888:8888"
        environment:
            # Jupyter runtime defaults
            JUPYTER_WORKING_DIR: /home/app/notebooks
            JUPYTER_PASSWD: jupyter
        volumes:
            - notebooks:/home/app/notebooks
            - application:/home/app/env/share/jupyter/lab
            - config:/home/app/.jupyter

volumes:
    notebooks:
    application:
    config:
